"""Nombres del equipo del SRD 3.5 en español.

Es una lista cerrada de 274 entradas, así que se traducen a mano una por una:
son términos consagrados en las mesas en español y adivinarlos con reglas daría
peores resultados que escribirlos.
"""

ARMAS = {
    'Gauntlet': 'Guantelete',
    'Unarmed strike': 'Ataque sin armas',
    'Dagger': 'Daga',
    'Dagger, punching': 'Daga de puño',
    'Gauntlet, spiked': 'Guantelete con púas',
    'Mace, light': 'Maza ligera',
    'Sickle': 'Hoz',
    'Club': 'Garrote',
    'Mace, heavy': 'Maza pesada',
    'Morningstar': 'Lucero del alba',
    'Shortspear': 'Lanza corta',
    'Longspear': 'Lanza larga',
    'Quarterstaff': 'Bastón',
    'Spear': 'Lanza',
    'Crossbow, heavy': 'Ballesta pesada',
    'Bolts, crossbow (10)': 'Virotes de ballesta (10)',
    'Crossbow, light': 'Ballesta ligera',
    'Dart': 'Dardo',
    'Javelin': 'Jabalina',
    'Sling': 'Honda',
    'Bullets, sling (10)': 'Balas de honda (10)',
    'Axe, throwing': 'Hacha arrojadiza',
    'Hammer, light': 'Martillo ligero',
    'Handaxe': 'Hacha de mano',
    'Kukri': 'Kukri',
    'Pick, light': 'Pico ligero',
    'Sap': 'Cachiporra',
    'Shield, light': 'Escudo ligero (como arma)',
    'Spiked armor': 'Armadura con púas (como arma)',
    'Spiked shield, light': 'Escudo ligero con púas',
    'Sword, short': 'Espada corta',
    'Battleaxe': 'Hacha de batalla',
    'Flail': 'Mayal',
    'Longsword': 'Espada larga',
    'Pick, heavy': 'Pico pesado',
    'Rapier': 'Estoque',
    'Scimitar': 'Cimitarra',
    'Shield, heavy': 'Escudo pesado (como arma)',
    'Spiked shield, heavy': 'Escudo pesado con púas',
    'Trident': 'Tridente',
    'Warhammer': 'Martillo de guerra',
    'Falchion': 'Alfanje',
    'Glaive': 'Gujía',
    'Greataxe': 'Hacha de guerra',
    'Greatclub': 'Garrote grande',
    'Flail, heavy': 'Mayal pesado',
    'Greatsword': 'Espadón',
    'Guisarme': 'Guisarma',
    'Halberd': 'Alabarda',
    'Lance': 'Lanza de caballería',
    'Ranseur': 'Ranseur',
    'Scythe': 'Guadaña',
    'Longbow': 'Arco largo',
    'Arrows (20)': 'Flechas (20)',
    'Longbow, composite': 'Arco largo compuesto',
    'Shortbow': 'Arco corto',
    'Shortbow, composite': 'Arco corto compuesto',
    'Kama': 'Kama',
    'Nunchaku': 'Nunchaku',
    'Sai': 'Sai',
    'Siangham': 'Siangham',
    'Sword, bastard': 'Espada bastarda',
    'Waraxe, dwarven': 'Hacha de guerra enana',
    'Whip': 'Látigo',
    'Axe, orc double': 'Hacha doble orca',
    'Chain, spiked': 'Cadena con púas',
    'Flail, dire': 'Mayal atroz',
    'Hammer, gnome hooked': 'Martillo gancho gnomo',
    'Sword, two-bladed': 'Espada de dos hojas',
    'Urgrosh, dwarven': 'Urgrosh enano',
    'Bolas': 'Bolas',
    'Crossbow, hand': 'Ballesta de mano',
    'Bolts (10)': 'Virotes (10)',
    'Crossbow, repeating heavy': 'Ballesta de repetición pesada',
    'Bolts (5)': 'Virotes (5)',
    'Crossbow, repeating light': 'Ballesta de repetición ligera',
    'Net': 'Red',
    'Shuriken (5)': 'Shuriken (5)',
}

ARMADURAS = {
    'Padded': 'Armadura acolchada',
    'Leather': 'Armadura de cuero',
    'Studded leather': 'Cuero tachonado',
    'Chain shirt': 'Camisote de mallas',
    'Hide': 'Armadura de pieles',
    'Scale mail': 'Cota de escamas',
    'Chainmail': 'Cota de mallas',
    'Breastplate': 'Coraza',
    'Splint mail': 'Cota de láminas',
    'Banded mail': 'Cota de bandas',
    'Half-plate': 'Media placa',
    'Full plate': 'Placas completas',
    'Buckler': 'Rodela',
    'Shield, light wooden': 'Escudo ligero de madera',
    'Shield, light steel': 'Escudo ligero de acero',
    'Shield, heavy wooden': 'Escudo pesado de madera',
    'Shield, heavy steel': 'Escudo pesado de acero',
    'Shield, tower': 'Escudo de torre',
    'Armor spikes': 'Púas de armadura',
    'Gauntlet, locked': 'Guantelete cerrado',
    'Shield spikes': 'Púas de escudo',
}

OBJETOS = {
    # --- equipo de aventurero ---
    'Backpack (empty)': 'Mochila (vacía)',
    'Barrel (empty)': 'Barril (vacío)',
    'Basket (empty)': 'Cesta (vacía)',
    'Bedroll': 'Petate',
    'Bell': 'Campanilla',
    'Blanket, winter': 'Manta de invierno',
    'Block and tackle': 'Polea con aparejo',
    'Bottle, wine, glass': 'Botella de vino de cristal',
    'Bucket (empty)': 'Cubo (vacío)',
    'Caltrops': 'Abrojos',
    'Candle': 'Vela',
    'Canvas (sq. yd.)': 'Lona (por metro cuadrado)',
    'Case, map or scroll': 'Estuche para mapas o pergaminos',
    'Chain (10 ft.)': 'Cadena (10 pies)',
    'Chalk, 1 piece': 'Tiza (una barra)',
    'Chest (empty)': 'Arcón (vacío)',
    'Crowbar': 'Palanqueta',
    'Firewood (per day)': 'Leña (por día)',
    'Fishhook': 'Anzuelo',
    'Fishing net, 25 sq. ft.': 'Red de pesca (25 pies cuadrados)',
    'Flask (empty)': 'Frasco (vacío)',
    'Flint and steel': 'Pedernal y acero',
    'Grappling hook': 'Garfio de escalada',
    'Hammer': 'Martillo',
    'Ink (1 oz. vial)': 'Tinta (frasco de 1 onza)',
    'Inkpen': 'Pluma de escribir',
    'Jug, clay': 'Jarra de barro',
    'Ladder, 10-foot': 'Escalera de 10 pies',
    'Lamp, common': 'Candil corriente',
    'Lantern, bullseye': 'Farol de ojo de buey',
    'Lantern, hooded': 'Farol con caperuza',
    'Lock (very simple)': 'Cerradura (muy sencilla)',
    'Lock (average)': 'Cerradura (corriente)',
    'Lock (good)': 'Cerradura (buena)',
    'Lock (amazing)': 'Cerradura (excepcional)',
    'Manacles': 'Grilletes',
    'Manacles, masterwork': 'Grilletes de calidad superior',
    'Mirror, small steel': 'Espejo pequeño de acero',
    'Mug/Tankard, clay': 'Jarra de barro para beber',
    'Oil (1-pint flask)': 'Aceite (frasco de una pinta)',
    'Paper (sheet)': 'Papel (una hoja)',
    'Parchment (sheet)': 'Pergamino (una hoja)',
    'Pick, miner’s': 'Piqueta de minero',
    'Pitcher, clay': 'Cántaro de barro',
    'Piton': 'Clavija de escalada',
    'Pole, 10-foot': 'Pértiga de 10 pies',
    'Pot, iron': 'Olla de hierro',
    'Pouch, belt (empty)': 'Bolsa de cinturón (vacía)',
    'Ram, portable': 'Ariete portátil',
    'Rations, trail (per day)': 'Raciones de viaje (por día)',
    'Rope, hempen (50 ft.)': 'Cuerda de cáñamo (50 pies)',
    'Rope, silk (50 ft.)': 'Cuerda de seda (50 pies)',
    'Sack (empty)': 'Saco (vacío)',
    'Sealing wax': 'Lacre',
    'Sewing needle': 'Aguja de coser',
    'Signal whistle': 'Silbato de señales',
    'Signet ring': 'Anillo de sello',
    'Sledge': 'Almádena',
    'Soap (per lb.)': 'Jabón (por libra)',
    'Spade or shovel': 'Pala o azada',
    'Spyglass': 'Catalejo',
    'Tent': 'Tienda de campaña',
    'Torch': 'Antorcha',
    'Vial, ink or potion': 'Vial para tinta o poción',
    'Waterskin': 'Odre',
    'Whetstone': 'Piedra de afilar',
    # --- sustancias y objetos especiales ---
    'Acid (flask)': 'Ácido (frasco)',
    'Alchemist’s fire (flask)': 'Fuego del alquimista (frasco)',
    'Antitoxin (vial)': 'Antitoxina (vial)',
    'Everburning torch': 'Antorcha eterna',
    'Holy water (flask)': 'Agua bendita (frasco)',
    'Smokestick': 'Vara de humo',
    'Sunrod': 'Vara solar',
    'Tanglefoot bag': 'Bolsa trabapiés',
    'Thunderstone': 'Piedra atronadora',
    'Tindertwig': 'Cerilla de yesca',
    # --- herramientas y estuches ---
    'Alchemist’s lab': 'Laboratorio de alquimista',
    'Artisan’s tools': 'Herramientas de artesano',
    'Artisan’s tools, masterwork': 'Herramientas de artesano de calidad superior',
    'Climber’s kit': 'Estuche de escalador',
    'Disguise kit': 'Estuche de disfraces',
    'Healer’s kit': 'Estuche de sanador',
    'Holly and mistletoe': 'Acebo y muérdago',
    'Holy symbol, wooden': 'Símbolo sagrado de madera',
    'Holy symbol, silver': 'Símbolo sagrado de plata',
    'Hourglass': 'Reloj de arena',
    'Magnifying glass': 'Lupa',
    'Musical instrument, common': 'Instrumento musical corriente',
    'Musical instrument, masterwork': 'Instrumento musical de calidad superior',
    'Scale, merchant’s': 'Balanza de mercader',
    'Spell component pouch': 'Bolsa de componentes',
    'Spellbook, wizard’s (blank)': 'Libro de conjuros de mago (en blanco)',
    'Thieves’ tools': 'Herramientas de ladrón',
    'Thieves’ tools, masterwork': 'Herramientas de ladrón de calidad superior',
    'Tool, masterwork': 'Herramienta de calidad superior',
    'Water clock': 'Reloj de agua',
    # --- ropa ---
    'Artisan’s outfit': 'Ropa de artesano',
    'Cleric’s vestments': 'Vestiduras de clérigo',
    'Cold weather outfit': 'Ropa de abrigo',
    'Courtier’s outfit': 'Ropa de cortesano',
    'Entertainer’s outfit': 'Ropa de artista',
    'Explorer’s outfit': 'Ropa de explorador',
    'Monk’s outfit': 'Ropa de monje',
    'Noble’s outfit': 'Ropa de noble',
    'Peasant’s outfit': 'Ropa de campesino',
    'Royal outfit': 'Ropa regia',
    'Scholar’s outfit': 'Ropa de erudito',
    'Traveler’s outfit': 'Ropa de viajero',
    # --- comida, bebida y alojamiento ---
    'Ale, gallon': 'Cerveza (galón)',
    'Ale, mug': 'Cerveza (jarra)',
    'Banquet (per person)': 'Banquete (por persona)',
    'Bread, per loaf': 'Pan (una hogaza)',
    'Cheese, hunk of': 'Queso (un pedazo)',
    'Inn stay (per day), good': 'Posada, buena (por día)',
    'Inn stay (per day), common': 'Posada, corriente (por día)',
    'Inn stay (per day), poor': 'Posada, mala (por día)',
    'Meals (per day), good': 'Comidas, buenas (por día)',
    'Meals (per day), common': 'Comidas, corrientes (por día)',
    'Meals (per day), poor': 'Comidas, malas (por día)',
    'Meat, chunk of': 'Carne (un pedazo)',
    'Wine, common (pitcher)': 'Vino corriente (jarra)',
    'Wine, fine (bottle)': 'Vino bueno (botella)',
    # --- monturas y arreos ---
    'Barding, medium creature': 'Barda para criatura mediana',
    'Barding, large creature': 'Barda para criatura grande',
    'Bit and bridle': 'Bocado y brida',
    'Dog, guard': 'Perro guardián',
    'Dog, riding': 'Perro de monta',
    'Donkey or mule': 'Burro o mula',
    'Feed (per day)': 'Pienso (por día)',
    'Horse, heavy': 'Caballo pesado',
    'Horse, light': 'Caballo ligero',
    'Pony': 'Poni',
    'Warhorse, heavy': 'Caballo de guerra pesado',
    'Warhorse, light': 'Caballo de guerra ligero',
    'Warpony': 'Poni de guerra',
    'Saddle, military': 'Silla de montar militar',
    'Saddle, pack': 'Silla de montar de carga',
    'Saddle, riding': 'Silla de montar de paseo',
    'Saddle, Exotic, military': 'Silla de montar exótica militar',
    'Saddle, Exotic, pack': 'Silla de montar exótica de carga',
    'Saddle, Exotic, riding': 'Silla de montar exótica de paseo',
    'Saddlebags': 'Alforjas',
    'Stabling (per day)': 'Establo (por día)',
    # --- transporte ---
    'Carriage': 'Carruaje',
    'Cart': 'Carro',
    'Galley': 'Galera',
    'Keelboat': 'Barcaza de quilla',
    'Longship': 'Drakkar',
    'Rowboat': 'Bote de remos',
    'Oar': 'Remo',
    'Sailing ship': 'Barco de vela',
    'Sled': 'Trineo',
    'Wagon': 'Carreta',
    'Warship': 'Barco de guerra',
    # --- conjuros y servicios ---
    'Coach cab': 'Coche de caballos',
    'Hireling, trained': 'Asalariado cualificado',
    'Hireling, untrained': 'Asalariado sin cualificar',
    'Messenger': 'Mensajero',
    'Road or gate toll': 'Peaje de camino o de puerta',
    'Ship’s passage': 'Pasaje en barco',
    'Spell, 0-level': 'Conjuro de nivel 0',
    'Spell, 1st-level': 'Conjuro de nivel 1',
    'Spell, 2nd-level': 'Conjuro de nivel 2',
    'Spell, 3rd-level': 'Conjuro de nivel 3',
    'Spell, 4th-level': 'Conjuro de nivel 4',
    'Spell, 5th-level': 'Conjuro de nivel 5',
    'Spell, 6th-level': 'Conjuro de nivel 6',
    'Spell, 7th-level': 'Conjuro de nivel 7',
    'Spell, 8th-level': 'Conjuro de nivel 8',
    'Spell, 9th-level': 'Conjuro de nivel 9',
}

TIPO_DANO = {
    'Bludgeoning': 'Contundente',
    'Piercing': 'Perforante',
    'Slashing': 'Cortante',
    'Bludgeoning and piercing': 'Contundente y perforante',
    'Bludgeoning/Piercing': 'Contundente o perforante',
    'Piercing or slashing': 'Perforante o cortante',
    'Slashing or piercing': 'Cortante o perforante',
    '—': '',
}

#

# los 8 objetos que ya estaban en el catálogo de Dorakan (V3), para no duplicarlos
# ni pisarles la descripción escrita a mano
YA_EXISTEN = {
    'Antorcha': 'antorcha',
    'Aceite (frasco de una pinta)': 'aceite',
    'Raciones de viaje (por día)': 'racion',
    'Piqueta de minero': 'piqueta',
    'Daga': 'daga',
    'Farol con caperuza': 'farol',
    'Cuerda de cáñamo (50 pies)': 'cuerda_canamo',
}
