"""Diccionario para traducir los nombres de las criaturas.

En inglés el núcleo va al final ("Dire Bear"); en español va delante y los
adjetivos detrás ("Oso atroz"), concordando en género. Por eso los sustantivos
llevan género y los adjetivos, forma masculina y femenina.

Muchos nombres son propios (Aboleth, Chuul, Xorn…) y no se traducen: se dejan
tal cual, que es como se leen en la mesa.
"""

# sustantivo -> (español, género)
NUCLEOS = {
    'Ant': ('Hormiga', 'f'), 'Ape': ('Simio', 'm'), 'Archon': ('Arconte', 'm'),
    'Badger': ('Tejón', 'm'), 'Bat': ('Murciélago', 'm'), 'Bear': ('Oso', 'm'),
    'Bee': ('Abeja', 'f'), 'Beetle': ('Escarabajo', 'm'), 'Beast': ('Bestia', 'f'),
    'Bison': ('Bisonte', 'm'), 'Boar': ('Jabalí', 'm'), 'Camel': ('Camello', 'm'),
    'Cat': ('Gato', 'm'), 'Centaur': ('Centauro', 'm'), 'Centipede': ('Ciempiés', 'm'),
    'Cheetah': ('Guepardo', 'm'), 'Crocodile': ('Cocodrilo', 'm'), 'Cube': ('Cubo', 'm'),
    'Devil': ('Diablo', 'm'), 'Dog': ('Perro', 'm'), 'Donkey': ('Burro', 'm'),
    'Dragon': ('Dragón', 'm'), 'Eagle': ('Águila', 'f'), 'Elemental': ('Elemental', 'm'),
    'Elephant': ('Elefante', 'm'), 'Elf': ('Elfo', 'm'), 'Dwarf': ('Enano', 'm'),
    'Fiend': ('Demonio', 'm'), 'Fungus': ('Hongo', 'm'), 'Giant': ('Gigante', 'm'),
    'Gnome': ('Gnomo', 'm'), 'Goblin': ('Trasgo', 'm'), 'Golem': ('Gólem', 'm'),
    'Hag': ('Bruja', 'f'), 'Halfling': ('Mediano', 'm'), 'Hawk': ('Halcón', 'm'),
    'Horse': ('Caballo', 'm'), 'Hound': ('Sabueso', 'm'), 'Hydra': ('Hidra', 'f'),
    'Hyena': ('Hiena', 'f'), 'Jelly': ('Gelatina', 'f'), 'Lion': ('León', 'm'),
    'Lizard': ('Lagarto', 'm'), 'Locust': ('Langosta', 'f'), 'Mantis': ('Mantis', 'f'),
    'Monkey': ('Mono', 'm'), 'Monster': ('Monstruo', 'm'), 'Mound': ('Montículo', 'm'),
    'Mule': ('Mula', 'f'), 'Mummy': ('Momia', 'f'), 'Naga': ('Naga', 'f'),
    'Object': ('Objeto', 'm'), 'Octopus': ('Pulpo', 'm'), 'Ogre': ('Ogro', 'm'),
    'Ooze': ('Cieno', 'm'), 'Orc': ('Orco', 'm'), 'Owl': ('Búho', 'm'),
    'Pony': ('Poni', 'm'), 'Porpoise': ('Marsopa', 'f'), 'Pudding': ('Pudin', 'm'),
    'Rat': ('Rata', 'f'), 'Raven': ('Cuervo', 'm'), 'Ray': ('Raya', 'f'),
    'Render': ('Desgarrador', 'm'), 'Rhinoceros': ('Rinoceronte', 'm'),
    'Scorpion': ('Escorpión', 'm'), 'Shark': ('Tiburón', 'm'), 'Snake': ('Serpiente', 'f'),
    'Spider': ('Araña', 'f'), 'Squid': ('Calamar', 'm'), 'Swarm': ('Enjambre', 'm'),
    'Tiger': ('Tigre', 'm'), 'Toad': ('Sapo', 'm'), 'Turtle': ('Tortuga', 'f'),
    'Vine': ('Enredadera', 'f'), 'Wasp': ('Avispa', 'f'), 'Weasel': ('Comadreja', 'f'),
    'Whale': ('Ballena', 'f'), 'Wolf': ('Lobo', 'm'), 'Wolverine': ('Glotón', 'm'),
    'Worm': ('Gusano', 'm'), 'Skeleton': ('Esqueleto', 'm'), 'Zombie': ('Zombi', 'm'),
    'Angel': ('Ángel', 'm'), 'Titan': ('Titán', 'm'), 'Unicorn': ('Unicornio', 'm'),
    'Vampire': ('Vampiro', 'm'), 'Spawn': ('Engendro', 'm'), 'Shadow': ('Sombra', 'f'),
    'Wraith': ('Aparición', 'f'), 'Spectre': ('Espectro', 'm'), 'Ghoul': ('Necrófago', 'm'),
    'Ghast': ('Necrófago superior', 'm'), 'Wight': ('Alma en pena', 'f'),
    'Harpy': ('Arpía', 'f'), 'Medusa': ('Medusa', 'f'), 'Minotaur': ('Minotauro', 'm'),
    'Pegasus': ('Pegaso', 'm'), 'Gargoyle': ('Gárgola', 'f'), 'Treant': ('Ent', 'm'),
    'Nymph': ('Ninfa', 'f'), 'Dryad': ('Dríade', 'f'), 'Satyr': ('Sátiro', 'm'),
    'Griffon': ('Grifo', 'm'), 'Hippogriff': ('Hipogrifo', 'm'),
    'Chimera': ('Quimera', 'f'), 'Basilisk': ('Basilisco', 'm'),
    'Cockatrice': ('Cocatriz', 'f'), 'Manticore': ('Mantícora', 'f'),
    'Gorgon': ('Gorgona', 'f'), 'Kraken': ('Kraken', 'm'), 'Roc': ('Roc', 'm'),
    'Wyvern': ('Guiverno', 'm'), 'Owlbear': ('Osobúho', 'm'),
    'Mimic': ('Mímico', 'm'), 'Imp': ('Diablillo', 'm'), 'Nightmare': ('Corcel infernal', 'm'),
    'Succubus': ('Súcubo', 'm'), 'Lemure': ('Lemur', 'm'), 'Warrior': ('guerrero', 'm'),
    'Wizard': ('mago', 'm'), 'Cleric': ('clérigo', 'm'), 'Fighter': ('guerrero', 'm'),
    'Barbarian': ('bárbaro', 'm'), 'Ranger': ('explorador', 'm'), 'Paladin': ('paladín', 'm'),
    'Blackguard': ('caballero negro', 'm'), 'Commoner': ('plebeyo', 'm'),
    'Mage': ('Mago', 'm'), 'Lord': ('Señor', 'm'), 'Hero': ('Héroe', 'm'),
    'Archer': ('Arquera', 'f'), 'Hunter': ('Cazador', 'm'), 'Charger': ('Corcel', 'm'),
    'Queen': ('Reina', 'f'), 'Worker': ('Obrera', 'f'), 'Soldier': ('Soldado', 'm'),
    'Taskmaster': ('Capataz', 'm'), 'Myrmarch': ('Mirmarca', 'm'),
    'Protector': ('Protector', 'm'), 'Guardian': ('Guardián', 'm'),
    'Stalker': ('Acechador', 'm'), 'Filcher': ('Ratero', 'm'), 'Marauder': ('Merodeador', 'm'),
    'Mouther': ('Bocazas', 'm'), 'Eater': ('Devorador', 'm'), 'Mastiff': ('Mastín', 'm'),
    'Warhound': ('Perro de guerra', 'm'), 'Warhorse': ('Caballo de guerra', 'm'),
    'Deva': ('Deva', 'm'), 'Planetar': ('Planetar', 'm'), 'Solar': ('Solar', 'm'),
    'Devourer': ('Devorador', 'm'), 'Digester': ('Digestor', 'm'), 'Delver': ('Excavador', 'm'),
    'Choker': ('Estrangulador', 'm'), 'Cloaker': ('Capa viviente', 'f'),
    'Howler': ('Aullador', 'm'), 'Roper': ('Amarrador', 'm'), 'Retriever': ('Recuperador', 'm'),
    'Viper': ('Víbora', 'f'), 'Constrictor': ('Constrictora', 'f'),
    'Wisp': ('Fuego fatuo', 'm'), 'Stag': ('Ciervo', 'm'),
}

# adjetivo/modificador -> (masculino, femenino). Van DETRÁS del núcleo.
MODS = {
    'Black': ('negro', 'negra'), 'Blue': ('azul', 'azul'), 'Green': ('verde', 'verde'),
    'Red': ('rojo', 'roja'), 'White': ('blanco', 'blanca'), 'Brass': ('de latón', 'de latón'),
    'Bronze': ('de bronce', 'de bronce'), 'Copper': ('de cobre', 'de cobre'),
    'Gold': ('de oro', 'de oro'), 'Silver': ('de plata', 'de plata'),
    'Golden': ('dorado', 'dorada'), 'Gray': ('gris', 'gris'), 'Purple': ('púrpura', 'púrpura'),
    'Violet': ('violeta', 'violeta'), 'Ochre': ('ocre', 'ocre'), 'Brown': ('pardo', 'parda'),
    'Polar': ('polar', 'polar'), 'Dire': ('atroz', 'atroz'), 'Monstrous': ('monstruoso', 'monstruosa'),
    'Giant': ('gigante', 'gigante'), 'Celestial': ('celestial', 'celestial'),
    'Fiendish': ('infernal', 'infernal'), 'Abyssal': ('abisal', 'abisal'),
    'Greater': ('mayor', 'mayor'), 'Lesser': ('menor', 'menor'), 'Minor': ('menor', 'menor'),
    'Elder': ('anciano', 'anciana'), 'Average': ('común', 'común'), 'Advanced': ('avanzado', 'avanzada'),
    'Fire': ('de fuego', 'de fuego'), 'Water': ('de agua', 'de agua'),
    'Air': ('de aire', 'de aire'), 'Earth': ('de tierra', 'de tierra'),
    'Ice': ('de hielo', 'de hielo'), 'Magma': ('de magma', 'de magma'),
    'Steam': ('de vapor', 'de vapor'), 'Dust': ('de polvo', 'de polvo'),
    'Salt': ('de sal', 'de sal'), 'Ooze': ('de cieno', 'de cieno'),
    'Stone': ('de piedra', 'de piedra'), 'Iron': ('de hierro', 'de hierro'),
    'Clay': ('de arcilla', 'de arcilla'), 'Flesh': ('de carne', 'de carne'),
    'Bone': ('óseo', 'ósea'), 'Barbed': ('erizado', 'erizada'), 'Bearded': ('barbudo', 'barbuda'),
    'Chain': ('de cadenas', 'de cadenas'), 'Horned': ('cornudo', 'cornuda'),
    'Pit': ('del foso', 'del foso'), 'Frost': ('de escarcha', 'de escarcha'),
    'Winter': ('invernal', 'invernal'), 'Cloud': ('de las nubes', 'de las nubes'),
    'Hill': ('de las colinas', 'de las colinas'), 'Storm': ('de las tormentas', 'de las tormentas'),
    'Sea': ('marino', 'marina'), 'Baleen': ('barbada', 'barbada'), 'Cachalot': ('cachalote', 'cachalote'),
    'Manta': ('manta', 'manta'), 'Blink': ('parpadeante', 'parpadeante'),
    'Shocker': ('eléctrico', 'eléctrica'), 'Monitor': ('monitor', 'monitor'),
    'Rust': ('oxidador', 'oxidadora'), 'Razor': ('navaja', 'navaja'),
    'Shambling': ('tambaleante', 'tambaleante'), 'Gibbering': ('farfullante', 'farfullante'),
    'Invisible': ('invisible', 'invisible'), 'Ethereal': ('etéreo', 'etérea'),
    'Phantom': ('fantasmal', 'fantasmal'), 'Phase': ('translúcida', 'translúcida'),
    'Shield': ('escudo', 'escudo'), 'Gelatinous': ('gelatinoso', 'gelatinosa'),
    'Assassin': ('asesina', 'asesina'), 'Praying': ('religiosa', 'religiosa'),
    'Bombardier': ('bombardero', 'bombardera'), 'Riding': ('de montar', 'de montar'),
    'War': ('de guerra', 'de guerra'), 'Heavy': ('pesado', 'pesada'), 'Light': ('ligero', 'ligera'),
    'Noble': ('noble', 'noble'), 'Flamebrother': ('hermano de llama', 'hermana de llama'),
    'Juvenile': ('joven', 'joven'), 'Adult': ('adulto', 'adulta'), 'Young': ('joven', 'joven'),
    'Dark': ('oscura', 'oscura'), 'Spirit': ('espiritual', 'espiritual'),
    'Guardian': ('guardiana', 'guardiana'), 'Night': ('nocturna', 'nocturna'),
    'Nessian': ('nesiano', 'nesiana'), 'Yeth': ('yeth', 'yeth'),
    'Chaos': ('del caos', 'del caos'), 'Dread': ('temible', 'temible'),
    'Hellwasp': ('avispa infernal', 'avispa infernal'),
    'Animated': ('animado', 'animada'), 'Human': ('humano', 'humana'),
    'Hybrid': ('híbrida', 'híbrida'), 'Bear': ('de oso', 'de oso'),
    'Wolf': ('de lobo', 'de lobo'), 'Boar': ('de jabalí', 'de jabalí'),
    'Tiger': ('de tigre', 'de tigre'), 'Rat': ('de rata', 'de rata'),
    'Trumpet': ('trompetero', 'trompetera'), 'Lantern': ('linterna', 'linterna'),
    'Hound': ('sabueso', 'sabueso'), 'Spider': ('de arañas', 'de arañas'),
    'Astral': ('astral', 'astral'), 'Formian': ('formiano', 'formiana'), 'Constrictor': ('constrictor', 'constrictora'), 'Tiny': ('diminuto', 'diminuta'),
    'Small': ('pequeño', 'pequeña'), 'Medium': ('mediano', 'mediana'),
    'Large': ('grande', 'grande'), 'Huge': ('enorme', 'enorme'),
    'Gargantuan': ('gargantuesco', 'gargantuesca'), 'Colossal': ('colosal', 'colosal'),
}

# nombres que se traducen enteros (o que se dejan tal cual por ser propios)
ENTEROS = {
    'Aboleth': 'Aboleth', 'Achaierai': 'Achaierai', 'Allip': 'Allip', 'Ankheg': 'Ankheg',
    'Annis': 'Annis', 'Aranea': 'Aranea', 'Athach': 'Athach', 'Avoral': 'Avoral',
    'Azer': 'Azer', 'Babau': 'Babau', 'Baboon': 'Babuino', 'Balor': 'Balor',
    'Barghest': 'Barghest', 'Bebilith': 'Bebilith', 'Behir': 'Behir', 'Belker': 'Belker',
    'Bodak': 'Bodak', 'Bralani': 'Bralani', 'Bugbear': 'Osgo', 'Bulette': 'Bulette',
    'Chuul': 'Chuul', 'Couatl': 'Couatl', 'Darkmantle': 'Manto oscuro',
    'Deinonychus': 'Deinonychus', 'Derro': 'Derro', 'Destrachan': 'Destrachan',
    'Djinni': 'Djinni', 'Doppelganger': 'Doppelganger', 'Dragonne': 'Dragonne',
    'Dretch': 'Dretch', 'Drider': 'Drider', 'Drow': 'Drow', 'Duergar': 'Duergar',
    'Efreeti': 'Efreeti', 'Elasmosaurus': 'Elasmosaurio', 'Erinyes': 'Erinia',
    'Ettercap': 'Ettercap', 'Ettin': 'Ettin', 'Formian': 'Formiano',
    'Ghaele': 'Ghaele', 'Girallon': 'Girallon', 'Glabrezu': 'Glabrezu',
    'Gnoll': 'Gnoll', 'Grick': 'Grick', 'Grig': 'Grig', 'Grimlock': 'Grimlock',
    'Hellcat': 'Gato infernal', 'Hellhound': 'Perro infernal', 'Hezrou': 'Hezrou',
    'Hobgoblin': 'Hobgoblin', 'Homunculus': 'Homúnculo', 'Janni': 'Janni',
    'Kobold': 'Kóbold', 'Kolyarut': 'Kolyarut', 'Krenshar': 'Krenshar',
    'Lamia': 'Lamia', 'Lammasu': 'Lammasu', 'Leonal': 'Leonal', 'Leopard': 'Leopardo',
    'Lillend': 'Lillend', 'Lizardfolk': 'Hombre lagarto', 'Locathah': 'Locathah',
    'Magmin': 'Magmín', 'Marilith': 'Marilith', 'Marut': 'Marut',
    'Megaraptor': 'Megarraptor', 'Mephit': 'Mefit', 'Merfolk': 'Tritón',
    'Mohrg': 'Mohrg', 'Nalfeshnee': 'Nalfeshnee', 'Nightcrawler': 'Reptador nocturno',
    'Nightwalker': 'Caminante nocturno', 'Nightwing': 'Ala nocturna', 'Nixie': 'Nixie',
    'Orca': 'Orca', 'Otyugh': 'Otyugh', 'Phasm': 'Phasm', 'Pixie': 'Duende',
    'Pseudodragon': 'Pseudodragón', 'Quasit': 'Quasit', 'Rakshasa': 'Rakshasa',
    'Rast': 'Rast', 'Ravid': 'Ravid', 'Remorhaz': 'Remorhaz', 'Sahuagin': 'Sahuagin',
    'Salamander': 'Salamandra', 'Scorpionfolk': 'Hombre escorpión', 'Skum': 'Skum',
    'Stirge': 'Estirge', 'Svirfneblin': 'Svirfneblin', 'Tarrasque': 'Tarrasca',
    'Tendriculos': 'Tendriculos', 'Thoqqua': 'Thoqqua', 'Tiefling': 'Tiefling',
    'Tojanida': 'Tojanida', 'Triceratops': 'Triceratops', 'Triton': 'Tritón marino',
    'Troglodyte': 'Troglodita', 'Troll': 'Troll', 'Tyrannosaurus': 'Tiranosaurio',
    'Vargouille': 'Vargouille', 'Vrock': 'Vrock', 'Worg': 'Worg', 'Xill': 'Xill',
    'Xorn': 'Xorn', 'Yrthak': 'Yrthak', 'Zelekhut': 'Zelekhut', 'Aasimar': 'Aasimar',
    'Gynosphinx': 'Ginoesfinge', 'Androsphinx': 'Androesfinge',
    'Criosphinx': 'Crioesfinge', 'Hieracosphinx': 'Hieracoesfinge',
    'Werebear': 'Hombre oso', 'Wereboar': 'Hombre jabalí', 'Wererat': 'Hombre rata',
    'Weretiger': 'Hombre tigre', 'Werewolf': 'Hombre lobo',
    'Arrowhawk': 'Halcón flecha', 'Owlbear': 'Osobúho',
    'Cauchemar': 'Cauchemar', 'Jarl': 'Jarl', 'Shrieker': 'Chillón',
    "Will-O'-Wisp": 'Fuego fatuo', 'Will-O\u2019-Wisp': 'Fuego fatuo',
}

# sufijos de tamaño y de edad que van tras la coma
SUFIJOS = {
    'Tiny': ('diminuto', 'diminuta'), 'Small': ('pequeño', 'pequeña'),
    'Medium': ('mediano', 'mediana'), 'Large': ('grande', 'grande'),
    'Huge': ('enorme', 'enorme'), 'Gargantuan': ('gargantuesco', 'gargantuesca'),
    'Colossal': ('colosal', 'colosal'), 'Greater': ('mayor', 'mayor'),
    'Elder': ('anciano', 'anciana'),
    'Wyrmling': ('cría', 'cría'), 'Very young': ('muy joven', 'muy joven'),
    'Young': ('joven', 'joven'), 'Juvenile': ('juvenil', 'juvenil'),
    'Young adult': ('adulto joven', 'adulta joven'), 'Adult': ('adulto', 'adulta'),
    'Mature adult': ('adulto maduro', 'adulta madura'), 'Old': ('viejo', 'vieja'),
    'Very old': ('muy viejo', 'muy vieja'), 'Ancient': ('anciano', 'anciana'),
    'Wyrm': ('wyrm', 'wyrm'), 'Great wyrm': ('gran wyrm', 'gran wyrm'),
}


# nombres compuestos que las reglas dejan torpes: aquí van a mano
EXCEPCIONES = {
    'Aboleth Mage, 10th-Level Wizard': 'Aboleth mago, mago de nivel 10',
    'Ogre Mage': 'Ogro mago',
    'Harpy Archer, 7th-Level Fighter': 'Arpía arquera, guerrera de nivel 7',
    'Hound Archon Hero, 11th-Level Paladin': 'Arconte sabueso héroe, paladín de nivel 11',
    'Mummy Lord, 10th-Level Cleric': 'Momia señora, clérigo de nivel 10',
    'Troll Hunter, 6th-Level Ranger': 'Troll cazador, explorador de nivel 6',
    'Werewolf Lord, Human Form': 'Señor hombre lobo, forma humana',
    'Werewolf Lord, Hybrid Form': 'Señor hombre lobo, forma híbrida',
    'Werewolf Lord, Dire Wolf Form': 'Señor hombre lobo, forma de lobo atroz',
    'Golden Protector (Celestial Half-Dragon Lammasu)':
        'Protector dorado (lammasu semidragón celestial)',
    'Hill Giant Dire Wereboar Dire Boar Form':
        'Hombre jabalí atroz gigante de las colinas, forma de jabalí atroz',
    'Hill Giant Dire Wereboar Giant Form':
        'Hombre jabalí atroz gigante de las colinas, forma de gigante',
    'Hill Giant Dire Wereboar Hybrid Boar Form':
        'Hombre jabalí atroz gigante de las colinas, forma híbrida de jabalí',
    'Giant Ant, Queen': 'Hormiga gigante, reina',
    'Giant Ant, Soldier': 'Hormiga gigante, soldado',
    'Giant Ant, Worker': 'Hormiga gigante, obrera',
    'Formian Warrior': 'Formiano guerrero',
    'Celestial Charger, 7th-Level Cleric': 'Corcel celestial, clérigo de nivel 7',
    'Frost Giant Jarl, 8th-Level Blackguard':
        'Jarl gigante de escarcha, caballero negro de nivel 8',
}
