"""Vocabulario del bloque de estadísticas de monstruos del SRD 3.5.

Casi todo el bloque es jerga cerrada: tamaños, tipos de criatura, habilidades,
dotes, cualidades especiales, terrenos, tesoro y alineamiento. Traduciéndola se
cubre el bloque entero; lo que queda en inglés son nombres propios.

TERMINOS se aplica de más largo a más corto para que "low-light vision" gane a
"vision", y siempre con límites de palabra.
"""

TAMANOS = {
    'Fine': 'menudo', 'Diminutive': 'diminuto', 'Tiny': 'minúsculo',
    'Small': 'pequeño', 'Medium-Size': 'mediano', 'Medium': 'mediano',
    'Large': 'grande', 'Huge': 'enorme', 'Gargantuan': 'gargantuesco',
    'Colossal': 'colosal',
}

TIPOS = {
    'Aberration': 'Aberración', 'Animal': 'Animal', 'Construct': 'Constructo',
    'Dragon': 'Dragón', 'Elemental': 'Elemental', 'Fey': 'Hada',
    'Giant': 'Gigante', 'Humanoid': 'Humanoide', 'Magical Beast': 'Bestia mágica',
    'Monstrous Humanoid': 'Humanoide monstruoso', 'Ooze': 'Cieno',
    'Outsider': 'Exterior', 'Plant': 'Planta', 'Undead': 'No muerto',
    'Vermin': 'Alimaña',
}

SUBTIPOS = {
    'Air': 'aire', 'Aquatic': 'acuático', 'Archon': 'arconte',
    'Augmented': 'aumentado', 'Baatezu': 'baatezu', 'Chaotic': 'caótico',
    'Cold': 'frío', 'Demon': 'demonio', 'Devil': 'diablo', 'Dwarf': 'enano',
    'Earth': 'tierra', 'Eladrin': 'eladrin', 'Elf': 'elfo', 'Evil': 'maligno',
    'Extraplanar': 'extraplanario', 'Fire': 'fuego', 'Goblinoid': 'trasgoide',
    'Gnome': 'gnomo', 'Good': 'bondadoso', 'Guardinal': 'guardinal',
    'Halfling': 'mediano', 'Human': 'humano', 'Incorporeal': 'incorpóreo',
    'Lawful': 'legal', 'Native': 'nativo', 'Orc': 'orco', 'Psionic': 'psiónico',
    'Reptilian': 'reptiliano', 'Shapechanger': 'cambiaformas',
    'Slaad': 'slaad', "Tanar'ri": "tanar'ri", 'Swarm': 'enjambre',
    'Water': 'agua', 'Yugoloth': 'yugoloth', 'Angel': 'ángel',
    'Formian': 'formiano', 'Inevitable': 'inevitable', 'Reptile': 'reptil',
    'Half-Dragon': 'semidragón', 'Half-Fiend': 'semidemonio',
    'Half-Celestial': 'semicelestial', 'Titan': 'titán', 'Werecreature': 'licántropo',
}

HABILIDADES = {
    'Appraise': 'Tasación', 'Balance': 'Equilibrio', 'Bluff': 'Engañar',
    'Climb': 'Trepar', 'Concentration': 'Concentración', 'Craft': 'Artesanía',
    'Decipher Script': 'Descifrar escritura', 'Diplomacy': 'Diplomacia',
    'Disable Device': 'Inutilizar mecanismo', 'Disguise': 'Disfrazarse',
    'Escape Artist': 'Escapismo', 'Forgery': 'Falsificar',
    'Gather Information': 'Reunir información', 'Handle Animal': 'Trato con animales',
    'Heal': 'Sanar', 'Hide': 'Esconderse', 'Intimidate': 'Intimidar',
    'Jump': 'Saltar', 'Knowledge': 'Conocimiento', 'Listen': 'Escuchar',
    'Move Silently': 'Moverse sigilosamente', 'Open Lock': 'Abrir cerraduras',
    'Perform': 'Interpretar', 'Profession': 'Profesión', 'Ride': 'Montar',
    'Search': 'Buscar', 'Sense Motive': 'Averiguar intenciones',
    'Sleight of Hand': 'Juego de manos', 'Spellcraft': 'Conocimiento de conjuros',
    'Spot': 'Avistar', 'Survival': 'Supervivencia', 'Swim': 'Nadar',
    'Tumble': 'Piruetas', 'Use Magic Device': 'Utilizar objeto mágico',
    'Use Rope': 'Uso de cuerdas', 'Speak Language': 'Hablar idioma',
}

DOTES = {
    'Ability Focus': 'Aptitud focalizada', 'Agile': 'Ágil', 'Alertness': 'Alerta',
    'Awesome Blow': 'Golpe imponente', 'Blind-Fight': 'Combatir a ciegas',
    'Cleave': 'Hendedura', 'Combat Casting': 'Lanzamiento en combate',
    'Combat Expertise': 'Pericia en combate', 'Combat Reflexes': 'Reflejos de combate',
    'Diehard': 'Duro de matar', 'Dodge': 'Esquiva',
    'Empower Spell-Like Ability': 'Potenciar aptitud sobrenatural',
    'Empower Spell': 'Potenciar conjuro', 'Endurance': 'Vigor',
    'Eschew Materials': 'Prescindir de materiales',
    'Exotic Weapon Proficiency': 'Competencia con armas exóticas',
    'Extend Spell': 'Extender conjuro', 'Extra Turning': 'Expulsión adicional',
    'Flyby Attack': 'Ataque en vuelo', 'Great Cleave': 'Gran hendedura',
    'Great Fortitude': 'Gran fortaleza', 'Hover': 'Cernerse',
    'Improved Bull Rush': 'Arrollar mejorado',
    'Improved Counterspell': 'Contraconjuro mejorado',
    'Improved Critical': 'Crítico mejorado', 'Improved Disarm': 'Desarmar mejorado',
    'Improved Grapple': 'Presa mejorada', 'Improved Initiative': 'Iniciativa mejorada',
    'Improved Multiattack': 'Ataque múltiple mejorado',
    'Improved Natural Armor': 'Armadura natural mejorada',
    'Improved Natural Attack': 'Ataque natural mejorado',
    'Improved Overrun': 'Atropellar mejorado', 'Improved Sunder': 'Romper mejorado',
    'Improved Trip': 'Derribo mejorado', 'Improved Turning': 'Expulsión mejorada',
    'Improved Two-Weapon Fighting': 'Combatir con dos armas mejorado',
    'Iron Will': 'Voluntad de hierro', 'Leadership': 'Liderazgo',
    'Lightning Reflexes': 'Reflejos felinos', 'Manyshot': 'Disparo múltiple',
    'Maximize Spell': 'Maximizar conjuro', 'Mobility': 'Movilidad',
    'Mounted Combat': 'Combate montado', 'Multiattack': 'Ataque múltiple',
    'Multiweapon Fighting': 'Combatir con varias armas',
    'Persuasive': 'Persuasivo', 'Point Blank Shot': 'Disparo a bocajarro',
    'Power Attack': 'Ataque poderoso', 'Precise Shot': 'Disparo certero',
    'Quick Draw': 'Desenvainado rápido',
    'Quicken Spell-Like Ability': 'Acelerar aptitud sobrenatural',
    'Quickened Spell-Like Ability': 'Aptitud sobrenatural acelerada',
    'Rapid Shot': 'Disparo rápido', 'Ride-By Attack': 'Ataque al paso',
    'Run': 'Correr', 'Scribe Scroll': 'Escribir pergamino',
    'Shot on the Run': 'Disparar en movimiento', 'Skill Focus': 'Habilidad focalizada',
    'Snatch': 'Arrebatar', 'Spell Focus': 'Conjuro focalizado',
    'Spell Penetration': 'Penetración de conjuros',
    'Spirited Charge': 'Carga vigorosa', 'Spring Attack': 'Ataque súbito',
    'Stealthy': 'Sigiloso', 'Toughness': 'Dureza', 'Track': 'Rastrear',
    'Two-Weapon Fighting': 'Combatir con dos armas',
    'Weapon Finesse': 'Soltura con un arma', 'Weapon Focus': 'Arma focalizada',
    'Weapon Specialization': 'Especialización con un arma',
    'Wingover': 'Viraje', 'item creation feat': 'dote de creación de objetos',
}

# cualidades y ataques especiales, terreno, tesoro, organización y demás jerga
TERMINOS = {
    # --- sentidos y defensas ---
    # aptitudes que quedaban sueltas
    'DR': 'RD', 'SR': 'RC', 'magic': 'mágico', 'cloudwalking': 'caminar sobre nubes',
    'feather fall': 'caída de pluma', 'sound imitation': 'imitar sonidos',
    'create/destroy water': 'crear/destruir agua', 'icewalking': 'caminar sobre hielo',
    'snow vision': 'visión en la nieve', 'gaseous form': 'forma gaseosa',
    'hive mind': 'mente colmena', 'fire': 'fuego', 'adults': 'adultos',
    'aura of menace': 'aura de amenaza', 'sneak attack': 'ataque furtivo',
    'change shape': 'cambiar de forma', 'poison use': 'uso de veneno',
    'dominate monster': 'dominar monstruo', 'dominated creature': 'criatura dominada',
    'smite good': 'castigar al bueno', 'smite evil': 'castigar al maligno',
    'protection from sonics': 'protección contra lo sónico',
    'summon demon': 'convocar demonio', 'summon devil': 'convocar diablo',
    'petrification': 'petrificación', 'alternate form': 'forma alternativa',
    'curse of lycanthropy': 'maldición de la licantropía',
    # oficios y rangos que salen en la organización
    'sergeants': 'sargentos', 'sergeant': 'sargento', 'lieutenants': 'tenientes',
    'lieutenant': 'teniente', 'captains': 'capitanes', 'captain': 'capitán',
    'chieftain': 'jefe', 'chieftains': 'jefes', 'shaman': 'chamán',
    'shamans': 'chamanes', 'sorcerers': 'hechiceros', 'sorcerer': 'hechicero',
    'clerics': 'clérigos', 'cleric': 'clérigo', 'adepts': 'adeptos', 'adept': 'adepto',
    'warriors': 'guerreros', 'warrior': 'guerrero', 'workers': 'obreras',
    'worker': 'obrera', 'fighters': 'guerreros', 'fighter': 'guerrero',
    'wizards': 'magos', 'wizard': 'mago', 'druids': 'druidas', 'druid': 'druida',
    'rangers': 'exploradores', 'ranger': 'explorador', 'rogues': 'pícaros',
    'rogue': 'pícaro', 'barbarians': 'bárbaros', 'barbarian': 'bárbaro',
    'monks': 'monjes', 'monk': 'monje', 'bards': 'bardos', 'bard': 'bardo',
    'paladins': 'paladines', 'paladin': 'paladín', 'taskmasters': 'capataces',
    'myrmarchs': 'mirmarcas', 'hunting party': 'partida de caza',
    'raiding party': 'partida de asalto', 'conscription': 'de leva',
    'each': 'cada una', 'member': 'miembro', 'hyenas': 'hienas',
    'griffons': 'grifos', 'rocs': 'rocs', 'wolves': 'lobos', 'worgs': 'worgs',
    'dogs': 'perros', 'apes': 'simios', 'bats': 'murciélagos', 'rats': 'ratas',
    'aquatic subtype': 'subtipo acuático', 'fire subtype': 'subtipo de fuego',
    'cold subtype': 'subtipo de frío', 'subtype': 'subtipo',
    'caster level': 'nivel de lanzador', 'mucus cloud': 'nube de mucosidad',
    'low-light vision': 'visión en la penumbra', 'darkvision': 'visión en la oscuridad',
    'blindsight': 'visión ciega', 'blindsense': 'percepción ciega',
    'tremorsense': 'percepción sísmica', 'scent': 'olfato',
    'all-around vision': 'visión periférica', 'see in darkness': 'ver en la oscuridad',
    'damage reduction': 'reducción de daño', 'spell resistance': 'resistencia a conjuros',
    'fast healing': 'curación acelerada', 'regeneration': 'regeneración',
    'turn resistance': 'resistencia a la expulsión',
    'spell immunity': 'inmunidad a conjuros', 'immunity to': 'inmunidad a',
    'immunities': 'inmunidades', 'resistance to': 'resistencia a',
    'vulnerability to': 'vulnerabilidad a', 'undead traits': 'rasgos de no muerto',
    'plant traits': 'rasgos de planta', 'construct traits': 'rasgos de constructo',
    'elemental traits': 'rasgos de elemental', 'ooze traits': 'rasgos de cieno',
    'vermin traits': 'rasgos de alimaña', 'incorporeal': 'incorpóreo',
    'natural cunning': 'astucia natural', 'freedom of movement': 'libertad de movimiento',
    'water breathing': 'respirar bajo el agua', 'amphibious': 'anfibio',
    'camouflage': 'camuflaje', 'light sensitivity': 'sensibilidad a la luz',
    'light blindness': 'ceguera por la luz', 'telepathy': 'telepatía',
    'spell-like abilities': 'aptitudes sobrenaturales',
    'spell-like ability': 'aptitud sobrenatural',
    'supernatural ability': 'aptitud sobrenatural',
    'fire subtype': 'subtipo de fuego', 'cold subtype': 'subtipo de frío',
    'electricity': 'electricidad', 'acid': 'ácido', 'sonic': 'sónico',
    'negative energy': 'energía negativa', 'positive energy': 'energía positiva',
    # --- ataques especiales ---
    'improved grab': 'presa mejorada', 'swallow whole': 'engullir entero',
    'breath weapon': 'arma de aliento', 'frightful presence': 'presencia aterradora',
    'energy drain': 'succión de energía', 'ability drain': 'succión de característica',
    'ability damage': 'daño a característica', 'create spawn': 'crear engendro',
    'constrict': 'constreñir', 'pounce': 'abalanzarse', 'trample': 'arrollar',
    'rake': 'zarpazo', 'rend': 'desgarrar', 'poison': 'veneno', 'disease': 'enfermedad',
    'paralysis': 'parálisis', 'petrification': 'petrificación', 'gaze': 'mirada',
    'summon': 'convocar', 'rock throwing': 'lanzamiento de rocas',
    'rock catching': 'atrapar rocas', 'psionics': 'psiónica', 'slime': 'baba',
    'stunning': 'aturdimiento', 'fear': 'miedo', 'charm': 'embrujo',
    'command undead': 'dominar no muertos', 'tail sweep': 'barrido de cola',
    'crush': 'aplastar', 'spores': 'esporas', 'web': 'telaraña', 'blood drain': 'succión de sangre',
    'distraction': 'distracción', 'wounding': 'herir',
    # --- ataques y armas ---
    'melee touch': 'cuerpo a cuerpo de contacto', 'ranged touch': 'a distancia de contacto',
    'incorporeal touch': 'contacto incorpóreo', 'melee': 'cuerpo a cuerpo',
    'ranged': 'a distancia', 'touch': 'contacto', 'bite': 'mordisco',
    'claws': 'garras', 'claw': 'garra', 'slam': 'embestida', 'gore': 'cornada',
    'sting': 'aguijón', 'tentacles': 'tentáculos', 'tentacle': 'tentáculo',
    'tail slap': 'coletazo', 'tail': 'cola', 'wings': 'alas', 'wing': 'ala',
    'hooves': 'pezuñas', 'hoof': 'pezuña', 'talons': 'garras', 'talon': 'garra',
    'pincers': 'pinzas', 'pincer': 'pinza', 'spines': 'púas', 'tongue': 'lengua',
    'ray': 'rayo', 'butt': 'testarazo', 'arrows': 'flechas',
    'masterwork': 'de calidad superior', 'greatsword': 'espadón',
    'longsword': 'espada larga', 'shortsword': 'espada corta', 'spear': 'lanza',
    'shortspear': 'lanza corta', 'longspear': 'lanza larga', 'sling': 'honda',
    'longbow': 'arco largo', 'shortbow': 'arco corto', 'composite longbow': 'arco largo compuesto',
    'composite shortbow': 'arco corto compuesto', 'dagger': 'daga', 'club': 'garrote',
    'greatclub': 'garrote grande', 'greataxe': 'hacha de guerra',
    'battleaxe': 'hacha de batalla', 'handaxe': 'hacha de mano', 'halberd': 'alabarda',
    'javelin': 'jabalina', 'morningstar': 'lucero del alba', 'scimitar': 'cimitarra',
    'trident': 'tridente', 'net': 'red', 'flail': 'mayal', 'heavy flail': 'mayal pesado',
    'mace': 'maza', 'heavy mace': 'maza pesada', 'light mace': 'maza ligera',
    'quarterstaff': 'bastón', 'warhammer': 'martillo de guerra', 'rapier': 'estoque',
    'falchion': 'alfanje', 'guisarme': 'guisarma', 'glaive': 'gujía',
    'ranseur': 'ranseur', 'whip': 'látigo', 'kukri': 'kukri', 'lance': 'lanza de caballería',
    'light crossbow': 'ballesta ligera', 'heavy crossbow': 'ballesta pesada',
    'crossbow': 'ballesta', 'bolts': 'virotes', 'unarmed strike': 'ataque sin armas',
    # --- CA y armaduras ---
    'flat-footed': 'desprevenido', 'natural': 'natural', 'deflection': 'desviación',
    'studded leather': 'cuero tachonado', 'leather': 'cuero', 'chain shirt': 'camisote de mallas',
    'chainmail': 'cota de mallas', 'scale mail': 'cota de escamas',
    'banded mail': 'cota de bandas', 'splint mail': 'cota de láminas',
    'half-plate': 'media placa', 'full plate': 'placas completas',
    'breastplate': 'coraza', 'hide armor': 'armadura de pieles', 'hide': 'pieles',
    'padded': 'acolchada', 'buckler': 'rodela', 'light shield': 'escudo ligero',
    'heavy shield': 'escudo pesado', 'tower shield': 'escudo de torre',
    'shield': 'escudo', 'armor': 'armadura', 'size': 'tamaño',
    # --- movimiento ---
    'squares': 'casillas', 'square': 'casilla', 'fly': 'volar', 'swim': 'nadar',
    'climb': 'trepar', 'burrow': 'excavar', 'perfect': 'perfecta', 'good': 'buena',
    'average': 'media', 'poor': 'mala', 'clumsy': 'torpe',
    "can't run": 'no puede correr', 'cannot run': 'no puede correr',
    # --- terreno ---
    'Any': 'Cualquiera', 'Underground': 'Subterráneo', 'Temperate': 'templado',
    'Warm': 'cálido', 'Cold': 'frío', 'forests': 'bosques', 'forest': 'bosque',
    'plains': 'llanuras', 'hills': 'colinas', 'mountains': 'montañas',
    'marshes': 'marismas', 'deserts': 'desiertos', 'aquatic': 'aguas',
    'land': 'tierra firme', 'Elemental Plane of': 'Plano elemental de',
    'Material Plane': 'Plano Material', 'Astral Plane': 'Plano Astral',
    'Ethereal Plane': 'Plano Etéreo', 'Plane of Shadow': 'Plano de las Sombras',
    'Infinite Layers of the Abyss': 'Capas Infinitas del Abismo',
    'Nine Hells of Baator': 'Nueve Infiernos de Baator',
    'Seven Mounting Heavens of Celestia': 'Siete Cielos Ascendentes de Celestia',
    'Windswept Depths of Pandemonium': 'Profundidades Ventosas de Pandemónium',
    'Bleak Eternity of Gehenna': 'Eternidad Lúgubre de Gehena',
    'Gray Waste of Hades': 'Yermo Gris del Hades',
    'Tarterian Depths of Carceri': 'Profundidades Tartáreas de Carceri',
    'Infernal Battlefield of Acheron': 'Campo de Batalla Infernal de Acheron',
    'Clockwork Nirvana of Mechanus': 'Nirvana Mecánico de Mecanus',
    'Peaceable Kingdoms of Arcadia': 'Reinos Pacíficos de Arcadia',
    'Blessed Fields of Elysium': 'Campos Benditos del Elíseo',
    'Wilderness of the Beastlands': 'Espesura de las Tierras Bestiales',
    'Olympian Glades of Arborea': 'Claros Olímpicos de Arborea',
    'Heroic Domains of Ysgard': 'Dominios Heroicos de Ysgard',
    'Ever-Changing Chaos of Limbo': 'Caos Cambiante del Limbo',
    'Twin Paradises of Bytopia': 'Paraísos Gemelos de Bytopia',
    'aligned plane': 'plano alineado', 'plane': 'plano',
    # --- organización ---
    'Solitary': 'Solitario', 'solitary': 'solitario', 'pair': 'pareja',
    'gang': 'cuadrilla', 'band': 'partida', 'troop': 'tropa', 'pack': 'manada',
    'flock': 'bandada', 'herd': 'rebaño', 'colony': 'colonia', 'tribe': 'tribu',
    'warband': 'partida de guerra', 'clutch': 'nidada', 'brood': 'camada',
    'family': 'familia', 'nest': 'nido', 'hive': 'colmena', 'cluster': 'grupo',
    'gathering': 'reunión', 'clan': 'clan', 'squad': 'escuadra', 'team': 'equipo',
    'slaver brood': 'camada de esclavistas', 'slaver': 'esclavista',
    'company': 'compañía', 'patrol': 'patrulla', 'swarm': 'enjambre',
    'offspring': 'crías', 'young': 'joven', 'mated pair': 'pareja apareada',
    'or': 'o', 'and': 'y', 'plus': 'más', 'with': 'con', 'per': 'por',
    'noncombatant': 'no combatiente', 'noncombatants': 'no combatientes',
    'leader': 'líder', 'leaders': 'líderes', 'of': 'de', 'any': 'cualquiera',
    # --- tesoro ---
    'None': 'Ninguno', 'Standard': 'Estándar', 'standard': 'estándar',
    'Double standard': 'Doble del estándar', 'Triple standard': 'Triple del estándar',
    'coins': 'monedas', 'goods': 'bienes', 'items': 'objetos',
    'No coins': 'Sin monedas', 'nonflammables only': 'solo lo no inflamable',
    'half': 'la mitad',
    # --- alineamiento ---
    'Always': 'Siempre', 'Usually': 'Normalmente', 'Often': 'A menudo',
    'lawful': 'legal', 'chaotic': 'caótico', 'neutral': 'neutral',
    'evil': 'maligno', 'good': 'bueno', 'alignment': 'alineamiento',
    # --- avance y varios ---
    'By character class': 'Por clase de personaje',
    'by character class': 'por clase de personaje',
    'see text': 'ver texto', 'See text': 'Ver texto',
    'Same as': 'Igual que', 'same as': 'igual que',
    'Fort': 'Fort', 'Ref': 'Ref', 'Will': 'Vol',
    'Str': 'Fue', 'Dex': 'Des', 'Con': 'Con', 'Int': 'Int', 'Wis': 'Sab', 'Cha': 'Car',
    'HD': 'DG', 'hp': 'pg', 'ft.': 'pies', 'lb.': 'lb', 'DC': 'CD',
    'Wyrmling': 'Cría', 'Very young': 'Muy joven', 'Young adult': 'Adulto joven',
    'Mature adult': 'Adulto maduro', 'Very old': 'Muy viejo', 'Great wyrm': 'Gran wyrm',
    'Juvenile': 'Juvenil', 'Ancient': 'Anciano', 'Adult': 'Adulto', 'Old': 'Viejo',
    'Wyrm': 'Wyrm',
    # aclaraciones entre paréntesis de habilidades
    'any one': 'una cualquiera', 'any two': 'dos cualesquiera', 'arcana': 'arcano',
    'nature': 'naturaleza', 'religion': 'religión', 'the planes': 'los planos',
    'dungeoneering': 'mazmorras', 'local': 'local', 'history': 'historia',
    'geography': 'geografía', 'nobility and royalty': 'nobleza y realeza',
    'architecture and engineering': 'arquitectura e ingeniería',
    'acting': 'actuando', 'in swamps': 'en pantanos', 'in forests': 'en bosques',
    'in rocky areas': 'en terreno rocoso', 'in tunnels': 'en túneles',
    'in water': 'en el agua', 'in its home': 'en su guarida',
}

# el terreno se dice al revés: "Warm deserts" -> "desiertos cálidos"
TERRENOS = {
    'forests': ('bosques', 'm', True), 'forest': ('bosque', 'm', False),
    'plains': ('llanuras', 'f', True), 'plain': ('llanura', 'f', False),
    'hills': ('colinas', 'f', True), 'hill': ('colina', 'f', False),
    'mountains': ('montañas', 'f', True), 'mountain': ('montaña', 'f', False),
    'marshes': ('marismas', 'f', True), 'marsh': ('marisma', 'f', False),
    'deserts': ('desiertos', 'm', True), 'desert': ('desierto', 'm', False),
    'aquatic': ('aguas', 'f', True), 'land': ('tierras', 'f', True),
}
CLIMAS = {'Temperate': ('templado', 'templada'), 'Warm': ('cálido', 'cálida'),
          'Cold': ('frío', 'fría')}
