-- =====================================================================
-- Las dotes del SRD 3.5 (contenido abierto OGL), de d20srd.org y traducidas
-- ENTERAS: a diferencia de los monstruos, una dote son dos o tres frases y en
-- inglés no sirve de nada en la mesa.
--
-- `feats` es el compendio (se consulta en la pestaña Habilidades) y
-- `character_feats` son las que tiene puestas un personaje en su ficha. La
-- segunda guarda un `detail` porque muchas dotes se eligen "para algo":
-- Arma focalizada (espada larga), Conjuro focalizado (Evocación)…
-- =====================================================================
create table if not exists feats (
    id           uuid primary key default gen_random_uuid(),
    name         varchar(120) not null unique,
    name_en      varchar(120) not null default '',
    -- General, Metamágica, Creación de objetos, Especial
    kind         varchar(40)  not null default 'General',
    prerequisite text         not null default '',
    benefit      text         not null default '',
    normal       text         not null default '',
    special      text         not null default '',
    source       varchar(60)  not null default 'SRD 3.5'
);

create index if not exists idx_feats_kind on feats(kind);

create table if not exists character_feats (
    id           uuid primary key default gen_random_uuid(),
    character_id uuid not null references characters(id) on delete cascade,
    -- el nombre visible; se copia para que la ficha siga entendiéndose
    -- aunque la dote se borre del compendio
    name         text not null,
    -- "espada larga", "Evocación"… vacío en las que no se especifican
    detail       text not null default '',
    -- enlace al compendio; null si es una dote de la casa
    feat_id      uuid references feats(id) on delete set null,
    sort_ordinal int  not null default 0
);

create index if not exists idx_character_feats_char on character_feats(character_id);

-- ---- el compendio de dotes ------------------------------------------
insert into feats (name, name_en, kind, prerequisite, benefit, normal, special) values
('Acrobático', 'Acrobatic', 'General', '', '+2 a todas las pruebas de Saltar y de Piruetas.', '', ''),
('Ágil', 'Agile', 'General', '', '+2 a todas las pruebas de Equilibrio y de Escapismo.', '', ''),
('Alerta', 'Alertness', 'General', '', '+2 a todas las pruebas de Escuchar y de Avistar.', '', 'El amo de un familiar disfruta de Alerta siempre que su familiar esté a un brazo de distancia.'),
('Afinidad animal', 'Animal Affinity', 'General', '', '+2 a todas las pruebas de Trato con animales y de Montar.', '', ''),
('Competencia con armadura (pesada)', 'Armor Proficiency (Heavy)', 'General', 'Competencia con armadura (ligera), Competencia con armadura (media).', 'Como Competencia con armadura (ligera), pero con las armaduras pesadas.', 'Ver Competencia con armadura (ligera).', 'Guerreros, paladines y clérigos la tienen de serie: no necesitan elegirla.'),
('Competencia con armadura (ligera)', 'Armor Proficiency (Light)', 'General', '', 'Con una armadura con la que eres competente, su penalizador de armadura solo se aplica a las pruebas de Equilibrio, Trepar, Escapismo, Esconderse, Saltar, Moverse sigilosamente, Juego de manos y Piruetas.', 'Quien lleva una armadura con la que no es competente aplica el penalizador de armadura a sus tiradas de ataque y a toda prueba de habilidad que implique moverse.', 'Todos los personajes salvo magos, hechiceros y monjes la tienen de serie.'),
('Competencia con armadura (media)', 'Armor Proficiency (Medium)', 'General', 'Competencia con armadura (ligera).', 'Como Competencia con armadura (ligera), pero con las armaduras medias.', 'Ver Competencia con armadura (ligera).', 'Guerreros, bárbaros, paladines, clérigos, druidas y bardos la tienen de serie.'),
('Atlético', 'Athletic', 'General', '', '+2 a todas las pruebas de Trepar y de Nadar.', '', ''),
('Convocación potenciada', 'Augment Summoning', 'General', 'Conjuro focalizado (Conjuración).', 'Toda criatura que convoques con un conjuro de convocación gana +4 de bonificador de mejora a Fuerza y Constitución mientras dure el conjuro.', '', ''),
('Combatir a ciegas', 'Blind-Fight', 'General', '', 'En cuerpo a cuerpo, cada vez que falles por ocultación puedes repetir una vez la tirada porcentual para ver si en realidad aciertas. Un atacante invisible no gana ninguna ventaja contra ti: no pierdes tu bonificador de Destreza a la CA y él no gana su +2 habitual. Además, te mueves a velocidad normal a oscuras.', 'Se aplican los modificadores normales de los atacantes invisibles y pierdes tu bonificador de Destreza a la CA.', 'No sirve de nada contra alguien afectado por parpadeo. Un guerrero puede elegirla como dote adicional de guerrero.'),
('Preparar pociones', 'Brew Potion', 'Creación de objetos', 'Nivel de lanzador 3.º.', 'Puedes crear una poción de cualquier conjuro de nivel 3 o menor que conozcas y que tenga por objetivo a una o más criaturas. Preparar una poción lleva un día. Su precio base es nivel del conjuro × nivel de lanzador × 50 po; cuesta 1/25 de ese precio en PX y la mitad en materiales.', '', ''),
('Hendedura', 'Cleave', 'General', 'Fue 13, Ataque poderoso.', 'Si haces caer a una criatura de un golpe, ganas al instante un ataque cuerpo a cuerpo adicional contra otra criatura a tu alcance, con la misma arma y el mismo bonificador. No puedes dar un paso de 5 pies antes de ese ataque. Una vez por asalto.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Lanzamiento en combate', 'Combat Casting', 'General', '', '+4 a las pruebas de Concentración para lanzar un conjuro o usar una aptitud sobrenatural mientras combates a la defensiva, o mientras estás en presa o inmovilizado.', '', ''),
('Pericia en combate', 'Combat Expertise', 'General', 'Int 13.', 'Al atacar en cuerpo a cuerpo puedes restar hasta 5 a todas tus tiradas de ataque y sumar esa misma cifra como bonificador de esquiva a tu CA. La cifra no puede superar tu bonificador de ataque base. Dura hasta tu siguiente acción.', 'Sin esta dote, combatir a la defensiva da −4 al ataque y +2 de esquiva a la CA.', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Reflejos de combate', 'Combat Reflexes', 'General', '', 'Puedes hacer tantos ataques de oportunidad adicionales como tu bonificador de Destreza. Además puedes hacerlos estando desprevenido.', 'Sin esta dote solo puedes hacer un ataque de oportunidad por asalto, y ninguno estando desprevenido.', 'No permite a un pícaro usar su aptitud de oportunista más de una vez por asalto. Un guerrero puede elegirla como dote adicional.'),
('Crear armas y armaduras mágicas', 'Craft Magic Arms And Armor', 'Creación de objetos', 'Nivel de lanzador 5.º.', 'Puedes crear cualquier arma, armadura o escudo mágico cuyos requisitos cumplas. Lleva un día por cada 1.000 po del precio de sus propiedades mágicas, cuesta 1/25 de ese precio en PX y la mitad en materiales. También puedes reparar objetos de este tipo que sepas fabricar.', '', ''),
('Crear varas', 'Craft Rod', 'Creación de objetos', 'Nivel de lanzador 9.º.', 'Puedes crear cualquier vara cuyos requisitos cumplas. Lleva un día por cada 1.000 po de su precio base, cuesta 1/25 de ese precio en PX y la mitad en materiales.', '', ''),
('Crear bastones', 'Craft Staff', 'Creación de objetos', 'Nivel de lanzador 12.º.', 'Puedes crear cualquier bastón cuyos requisitos cumplas. Lleva un día por cada 1.000 po de su precio base, cuesta 1/25 en PX y la mitad en materiales. Un bastón recién creado tiene 50 cargas.', '', ''),
('Crear varitas', 'Craft Wand', 'Creación de objetos', 'Nivel de lanzador 5.º.', 'Puedes crear una varita de cualquier conjuro de nivel 4 o menor que conozcas. Su precio base es nivel de lanzador × nivel del conjuro × 750 po; lleva un día por cada 1.000 po, cuesta 1/25 en PX y la mitad en materiales. Nace con 50 cargas.', '', ''),
('Crear objeto maravilloso', 'Craft Wondrous Item', 'Creación de objetos', 'Nivel de lanzador 3.º.', 'Puedes crear cualquier objeto maravilloso cuyos requisitos cumplas. Lleva un día por cada 1.000 po de su precio, cuesta 1/25 en PX y la mitad en materiales. También puedes reparar uno roto que supieras fabricar.', '', ''),
('Embustero', 'Deceitful', 'General', '', '+2 a todas las pruebas de Disfrazarse y de Falsificar.', '', ''),
('Desviar flechas', 'Deflect Arrows', 'General', 'Des 13, Ataque sin armas mejorado.', 'Con al menos una mano libre, una vez por asalto puedes desviar un proyectil que fuera a alcanzarte y no recibir ningún daño. Debes ser consciente del ataque y no estar desprevenido. Desviar no cuenta como acción. No sirve contra proyectiles enormes (rocas de gigante, virotes de balista) ni contra efectos mágicos.', '', 'Un monje puede tomarla como dote adicional a nivel 2 aunque no cumpla los requisitos. Un guerrero puede elegirla como dote adicional.'),
('Manos hábiles', 'Deft Hands', 'General', '', '+2 a todas las pruebas de Juego de manos y de Uso de cuerdas.', '', ''),
('Duro de matar', 'Diehard', 'General', 'Vigor.', 'Al quedarte entre −1 y −9 puntos de golpe te estabilizas automáticamente: no tiras d% cada asalto. Además puedes elegir actuar como si estuvieras incapacitado en vez de moribundo; si lo haces, cada acción agotadora te cuesta 1 punto de golpe más.', 'Sin esta dote, quien queda entre −1 y −9 puntos de golpe está inconsciente y moribundo.', ''),
('Diligente', 'Diligent', 'General', '', '+2 a todas las pruebas de Tasación y de Descifrar escritura.', '', '')
on conflict (name) do nothing;
insert into feats (name, name_en, kind, prerequisite, benefit, normal, special) values
('Esquiva', 'Dodge', 'General', 'Des 13.', 'En tu acción designas a un enemigo y ganas +1 de esquiva a la CA contra sus ataques. Puedes cambiar de enemigo en cualquier acción. Los bonificadores de esquiva se acumulan entre sí, y se pierden cuando pierdes tu bonificador de Destreza a la CA.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Potenciar conjuro', 'Empower Spell', 'Metamágica', '', 'Todos los efectos numéricos variables del conjuro aumentan la mitad. No afecta a las salvaciones ni a las tiradas enfrentadas. Ocupa un espacio de conjuro dos niveles por encima del suyo.', '', ''),
('Vigor', 'Endurance', 'General', '', '+4 a: Nadar para resistir daño no letal; pruebas de Constitución para seguir corriendo, para evitar el daño de una marcha forzada, para aguantar la respiración y para resistir hambre o sed; Fortaleza para aguantar calor o frío y para resistir el daño de correr con armadura. Además puedes dormir con armadura media o pesada sin quedar fatigado.', 'Quien duerme con armadura media o más pesada sin esta dote amanece fatigado.', 'Un explorador la gana de serie a nivel 3.'),
('Ampliar conjuro', 'Enlarge Spell', 'Metamágica', '', 'Un conjuro de alcance cercano, medio o largo duplica su alcance: cercano pasa a 50 pies + 5 pies/nivel, medio a 200 + 20/nivel y largo a 800 + 80/nivel. Ocupa un espacio un nivel por encima del suyo.', '', ''),
('Prescindir de materiales', 'Eschew Materials', 'General', '', 'Puedes lanzar cualquier conjuro cuyo componente material cueste 1 po o menos sin necesidad de ese componente. Si cuesta más de 1 po, sigues necesitándolo.', '', ''),
('Competencia con armas exóticas', 'Exotic Weapon Proficiency', 'General', 'Ataque base +1 (y Fue 13 para la espada bastarda o el hacha de guerra enana).', 'Haces las tiradas de ataque con esa arma con normalidad.', 'Quien usa un arma con la que no es competente sufre −4 al ataque.', 'Puedes tomarla varias veces, cada una para un arma exótica distinta.'),
('Extender conjuro', 'Extend Spell', 'Metamágica', '', 'El conjuro dura el doble. No afecta a los de duración concentración, instantánea o permanente. Ocupa un espacio un nivel por encima del suyo.', '', ''),
('Expulsión adicional', 'Extra Turning', 'General', 'Poder expulsar o reprender criaturas.', 'Puedes usar tu aptitud de expulsar o reprender cuatro veces más al día de lo normal. Si puedes expulsar a más de un tipo de criatura, cada aptitud gana cuatro usos.', 'Sin esta dote se expulsa 3 + modificador de Carisma veces al día.', 'Puedes tomarla varias veces y sus efectos se acumulan.'),
('Disparo lejano', 'Far Shot', 'General', 'Disparo a bocajarro.', 'Con un arma de proyectiles su incremento de distancia aumenta la mitad (×1½). Con un arma arrojadiza, se duplica.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Forjar anillos', 'Forge Ring', 'Creación de objetos', 'Nivel de lanzador 12.º.', 'Puedes crear cualquier anillo cuyos requisitos cumplas. Lleva un día por cada 1.000 po de su precio base, cuesta 1/25 en PX y la mitad en materiales. También puedes reparar uno roto que supieras fabricar.', '', ''),
('Gran hendedura', 'Great Cleave', 'General', 'Fue 13, Hendedura, Ataque poderoso, ataque base +4.', 'Como Hendedura, pero sin límite de veces por asalto.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Gran fortaleza', 'Great Fortitude', 'General', '', '+2 a todas las salvaciones de Fortaleza.', '', ''),
('Conjuro focalizado mayor', 'Greater Spell Focus', 'General', 'Conjuro focalizado en esa escuela.', '+1 más a la CD de las salvaciones contra tus conjuros de la escuela elegida. Se acumula con Conjuro focalizado.', '', 'Puedes tomarla varias veces, cada una para otra escuela en la que ya tengas Conjuro focalizado.'),
('Penetración de conjuros mayor', 'Greater Spell Penetration', 'General', 'Penetración de conjuros.', '+2 más a las pruebas de nivel de lanzador (1d20 + nivel) para superar la resistencia a conjuros. Se acumula con Penetración de conjuros.', '', ''),
('Combatir con dos armas mayor', 'Greater Two-Weapon Fighting', 'General', 'Des 19, Combatir con dos armas mejorado, Combatir con dos armas, ataque base +11.', 'Ganas un tercer ataque con el arma secundaria, con −10 al ataque.', '', 'Un guerrero puede elegirla como dote adicional. Un explorador de nivel 11 con el estilo de dos armas la tiene aunque no cumpla los requisitos.'),
('Arma focalizada mayor', 'Greater Weapon Focus', 'General', 'Competencia con el arma, Arma focalizada con ella, nivel de guerrero 8.º.', '+1 más a las tiradas de ataque con el arma elegida. Se acumula con Arma focalizada.', '', 'Puedes tomarla varias veces, cada una para un arma distinta.'),
('Especialización con un arma mayor', 'Greater Weapon Specialization', 'General', 'Competencia con el arma, Arma focalizada mayor, Arma focalizada y Especialización con ella, nivel de guerrero 12.º.', '+2 más a las tiradas de daño con el arma elegida. Se acumula con Especialización con un arma.', '', 'Puedes tomarla varias veces, cada una para un arma distinta.'),
('Elevar conjuro', 'Heighten Spell', 'Metamágica', '', 'El conjuro pasa a ser de un nivel superior (hasta 9 como máximo). A diferencia de otras dotes metamágicas, sube de verdad su nivel efectivo: la CD de la salvación y todo lo que dependa del nivel se calculan con el nuevo.', '', ''),
('Arrollar mejorado', 'Improved Bull Rush', 'General', 'Fue 13, Ataque poderoso.', 'Al arrollar no provocas ataque de oportunidad del defensor, y ganas +4 a la prueba enfrentada de Fuerza para empujarlo.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Contraconjuro mejorado', 'Improved Counterspell', 'General', '', 'Puedes contrarrestar un conjuro con otro de su misma escuela y de nivel igual o superior.', 'Sin esta dote solo puedes contrarrestar un conjuro con ese mismo conjuro o con el que se indique.', ''),
('Crítico mejorado', 'Improved Critical', 'General', 'Competencia con el arma, ataque base +8.', 'Con el arma elegida, tu margen de amenaza se duplica.', '', 'Puedes tomarla varias veces, cada una para un arma distinta. No se acumula con otros efectos que amplíen el margen de amenaza.'),
('Desarmar mejorado', 'Improved Disarm', 'General', 'Int 13, Pericia en combate.', 'Al desarmar no provocas ataque de oportunidad ni das al rival la ocasión de desarmarte a ti, y ganas +4 a la tirada de ataque enfrentada.', 'Ver las reglas normales de desarmar.', 'Un guerrero puede elegirla como dote adicional. Un monje puede tomarla a nivel 6 aunque no cumpla los requisitos.'),
('Familiar mejorado', 'Improved Familiar', 'General', 'Poder conseguir un familiar nuevo, alineamiento compatible y nivel suficiente.', 'Al elegir familiar puedes escoger también entre criaturas más poderosas de la lista, con un alineamiento que se aparte hasta un paso del tuyo en cada eje.', '', ''),
('Finta mejorada', 'Improved Feint', 'General', 'Int 13, Pericia en combate.', 'Puedes hacer una prueba de Engañar para fintar en combate como acción de movimiento.', 'Fintar en combate es una acción estándar.', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Presa mejorada', 'Improved Grapple', 'General', 'Des 13, Ataque sin armas mejorado.', 'No provocas ataque de oportunidad al hacer el ataque de contacto para iniciar una presa, y ganas +4 a todas las pruebas de presa.', 'Sin esta dote provocas un ataque de oportunidad al iniciar una presa.', 'Un guerrero puede elegirla como dote adicional. Un monje puede tomarla a nivel 1 aunque no cumpla los requisitos.')
on conflict (name) do nothing;
insert into feats (name, name_en, kind, prerequisite, benefit, normal, special) values
('Iniciativa mejorada', 'Improved Initiative', 'General', '', '+4 a las pruebas de iniciativa.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Atropellar mejorado', 'Improved Overrun', 'General', 'Fue 13, Ataque poderoso.', 'Al atropellar, el objetivo no puede elegir apartarse, y ganas +4 a la prueba de Fuerza para derribarlo.', 'Sin esta dote, el objetivo puede apartarse o bloquearte.', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Disparo certero mejorado', 'Improved Precise Shot', 'General', 'Des 19, Disparo a bocajarro, Disparo certero, ataque base +11.', 'Tus ataques a distancia ignoran el bonificador a la CA por cualquier cobertura que no sea total y la probabilidad de fallo por cualquier ocultación que no sea total. Además, al disparar a alguien trabado en una presa no hay riesgo de alcanzar a otro.', 'Ver las reglas normales de cobertura y ocultación.', 'Un guerrero puede elegirla como dote adicional. Un explorador de nivel 11 con el estilo de arquería la tiene aunque no cumpla los requisitos.'),
('Golpe de escudo mejorado', 'Improved Shield Bash', 'General', 'Competencia con escudos.', 'Al golpear con el escudo conservas su bonificador a la CA.', 'Sin esta dote pierdes el bonificador del escudo a la CA hasta tu siguiente turno.', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Romper mejorado', 'Improved Sunder', 'General', 'Fue 13, Ataque poderoso.', 'Al golpear un objeto que lleve un rival no provocas ataque de oportunidad, y ganas +4 a esa tirada de ataque.', 'Sin esta dote provocas un ataque de oportunidad al golpear un objeto que otro lleve encima.', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Derribo mejorado', 'Improved Trip', 'General', 'Int 13, Pericia en combate.', 'No provocas ataque de oportunidad al intentar derribar a un rival estando desarmado, y ganas +4 a la prueba de Fuerza para derribarlo. Si lo derribas, ganas al instante un ataque cuerpo a cuerpo contra él, como si no hubieras usado tu ataque.', 'Sin esta dote provocas un ataque de oportunidad al intentar derribar desarmado.', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Expulsión mejorada', 'Improved Turning', 'General', 'Poder expulsar o reprender criaturas.', 'Expulsas o reprendes como si tuvieras un nivel más en la clase que te da esa aptitud.', '', ''),
('Combatir con dos armas mejorado', 'Improved Two-Weapon Fighting', 'General', 'Des 17, Combatir con dos armas, ataque base +6.', 'Además del ataque adicional normal con el arma secundaria, ganas un segundo ataque con ella, con −5 al ataque.', 'Sin esta dote solo consigues un ataque adicional con el arma secundaria.', 'Un guerrero puede elegirla como dote adicional. Un explorador de nivel 6 con el estilo de dos armas la tiene aunque no cumpla los requisitos.'),
('Ataque sin armas mejorado', 'Improved Unarmed Strike', 'General', '', 'Se te considera armado aun estando desarmado: no provocas ataques de oportunidad al atacar sin armas, pero sí los provocas tú contra quien te ataque desarmado. Además, tus golpes sin armas pueden hacer daño letal o no letal, a tu elección.', 'Sin esta dote se te considera desarmado y solo puedes hacer daño no letal.', 'Un monje la gana de serie a nivel 1. Un guerrero puede elegirla como dote adicional.'),
('Investigador', 'Investigator', 'General', '', '+2 a todas las pruebas de Reunir información y de Buscar.', '', ''),
('Voluntad de hierro', 'Iron Will', 'General', '', '+2 a todas las salvaciones de Voluntad.', '', ''),
('Liderazgo', 'Leadership', 'General', 'Nivel de personaje 6.º.', 'Atraes a un lugarteniente y a un grupo de seguidores leales. Tu puntuación de liderazgo es tu nivel de personaje más tu modificador de Carisma, ajustada por tu reputación, tu fortaleza y cómo trates a los tuyos. Esa puntuación decide el nivel del lugarteniente (siempre dos niveles por debajo del tuyo como máximo) y cuántos seguidores de cada nivel te siguen. Consulta la tabla de Liderazgo del manual para las cifras exactas.', '', 'Un lugarteniente muerto o maltratado hace bajar tu puntuación de liderazgo.'),
('Reflejos felinos', 'Lightning Reflexes', 'General', '', '+2 a todas las salvaciones de Reflejos.', '', ''),
('Aptitud mágica', 'Magical Aptitude', 'General', '', '+2 a todas las pruebas de Conocimiento de conjuros y de Utilizar objeto mágico.', '', ''),
('Disparo múltiple', 'Manyshot', 'General', 'Des 17, Disparo a bocajarro, Disparo rápido, ataque base +6.', 'Como acción estándar puedes disparar dos flechas a un mismo objetivo a 30 pies o menos. Ambas usan la misma tirada de ataque, con −4, y hacen daño normal. Por cada 5 puntos de ataque base por encima de +6 puedes añadir una flecha más (hasta cuatro con ataque base +16), con −2 más al ataque por cada una.', '', 'Un guerrero puede elegirla como dote adicional. Un explorador de nivel 6 con el estilo de arquería la tiene aunque no cumpla los requisitos.'),
('Competencia con armas marciales', 'Martial Weapon Proficiency', 'General', '', 'Haces las tiradas de ataque con el arma elegida con normalidad.', 'Con un arma con la que no eres competente sufres −4 al ataque.', 'Puedes tomarla varias veces, cada una para un arma marcial distinta. Bárbaros, guerreros, paladines y exploradores son competentes con todas de serie.'),
('Maximizar conjuro', 'Maximize Spell', 'Metamágica', '', 'Todos los efectos numéricos variables del conjuro salen al máximo. No afecta a las salvaciones ni a las tiradas enfrentadas. Ocupa un espacio tres niveles por encima del suyo.', '', ''),
('Movilidad', 'Mobility', 'General', 'Des 13, Esquiva.', '+4 de esquiva a la CA contra los ataques de oportunidad que provoques al salir de un área amenazada o al moverte dentro de ella.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Arquería montada', 'Mounted Archery', 'General', 'Montar 1 rango, Combate montado.', 'El penalizador por usar un arma a distancia montado se reduce a la mitad: −2 en vez de −4 si tu montura hace un movimiento doble, y −4 en vez de −8 si corre.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Combate montado', 'Mounted Combat', 'General', 'Montar 1 rango.', 'Una vez por asalto, cuando alcancen a tu montura, puedes hacer una prueba de Montar como reacción para anular el impacto: se anula si tu resultado supera la tirada de ataque del rival.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Conjuro natural', 'Natural Spell', 'General', 'Sab 13, aptitud de forma salvaje.', 'Puedes completar los componentes verbales y somáticos de tus conjuros en forma salvaje, sustituyéndolos por ruidos y gestos. También puedes usar los componentes materiales y focos que lleves, aunque estén fundidos en tu forma actual.', '', ''),
('Negociador', 'Negotiator', 'General', '', '+2 a todas las pruebas de Diplomacia y de Averiguar intenciones.', '', ''),
('Dedos ágiles', 'Nimble Fingers', 'General', '', '+2 a todas las pruebas de Inutilizar mecanismo y de Abrir cerraduras.', '', ''),
('Persuasivo', 'Persuasive', 'General', '', '+2 a todas las pruebas de Engañar y de Intimidar.', '', ''),
('Disparo a bocajarro', 'Point Blank Shot', 'General', '', '+1 al ataque y al daño con armas a distancia contra blancos a 30 pies o menos.', '', '')
on conflict (name) do nothing;
insert into feats (name, name_en, kind, prerequisite, benefit, normal, special) values
('Ataque poderoso', 'Power Attack', 'General', 'Fue 13.', 'Antes de tirar tus ataques del asalto puedes restar una cifra a todas tus tiradas de ataque cuerpo a cuerpo y sumar esa misma cifra a todas las de daño. No puede superar tu bonificador de ataque base y dura hasta tu siguiente turno.', '', 'Con un arma a dos manos (o una a una mano usada a dos manos) sumas el DOBLE al daño. No sirve con armas ligeras. Un guerrero puede elegirla como dote adicional.'),
('Disparo certero', 'Precise Shot', 'General', 'Disparo a bocajarro.', 'Puedes disparar o arrojar contra un enemigo trabado en cuerpo a cuerpo sin el −4 habitual.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Desenvainado rápido', 'Quick Draw', 'General', 'Ataque base +1.', 'Desenvainas como acción libre en vez de como acción de movimiento, y sacas un arma escondida como acción de movimiento. Además puedes arrojar armas a tu ritmo completo de ataques.', 'Sin esta dote desenvainar es una acción de movimiento (o libre si tu ataque base es +1 o más, como parte de un movimiento).', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Acelerar conjuro', 'Quicken Spell', 'Metamágica', '', 'Lanzar el conjuro es una acción inmediata: puedes hacer otra cosa, incluso lanzar otro conjuro, en el mismo asalto. Solo uno acelerado por asalto, y no vale con conjuros de más de un asalto completo. Ocupa un espacio cuatro niveles por encima del suyo.', '', ''),
('Recarga rápida', 'Rapid Reload', 'General', 'Competencia con la ballesta elegida.', 'Recargar esa ballesta pasa a ser una acción libre (de mano o ligera) o de movimiento (pesada). Sigue provocando ataques de oportunidad. Con ballesta de mano o ligera puedes además disparar tantas veces por asalto como con un arco.', 'Sin esta dote hace falta una acción de movimiento para la de mano o ligera, y una de asalto completo para la pesada.', 'Puedes tomarla varias veces, cada una para otro tipo de ballesta.'),
('Disparo rápido', 'Rapid Shot', 'General', 'Des 13, Disparo a bocajarro.', 'Ganas un ataque a distancia adicional por asalto, con tu mejor bonificador de ataque base, pero todos tus ataques del asalto sufren −2. Requiere la acción de ataque completo.', '', 'Un guerrero puede elegirla como dote adicional. Un explorador de nivel 2 con el estilo de arquería la tiene aunque no cumpla los requisitos.'),
('Ataque al paso', 'Ride-By Attack', 'General', 'Montar 1 rango, Combate montado.', 'Montado y cargando, puedes moverte, atacar y seguir moviéndote en la misma línea recta, sin superar el doble de la velocidad de tu montura. Ni tú ni ella provocáis ataque de oportunidad del enemigo al que atacas.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Correr', 'Run', 'General', '', 'Al correr te mueves cinco veces tu velocidad (con armadura ligera, media o ninguna y carga media o menor), o cuatro veces con armadura pesada o carga pesada. Ganas +4 a Saltar tras una carrerilla y conservas tu bonificador de Destreza a la CA mientras corres.', 'Sin esta dote corres a cuatro veces tu velocidad (o tres con armadura pesada) y pierdes tu bonificador de Destreza a la CA.', ''),
('Escribir pergamino', 'Scribe Scroll', 'Creación de objetos', 'Nivel de lanzador 1.º.', 'Puedes crear un pergamino de cualquier conjuro que conozcas. Su precio base es nivel del conjuro × nivel de lanzador × 25 po; lleva un día por cada 1.000 po, cuesta 1/25 en PX y la mitad en materiales.', '', ''),
('Autosuficiente', 'Self-Sufficient', 'General', '', '+2 a todas las pruebas de Sanar y de Supervivencia.', '', ''),
('Competencia con escudos', 'Shield Proficiency', 'General', '', 'Puedes usar un escudo sufriendo solo los penalizadores normales.', 'Con un escudo con el que no eres competente aplicas su penalizador de armadura a las tiradas de ataque y a las pruebas de habilidad que impliquen moverse.', 'Todos salvo magos, hechiceros, druidas y monjes la tienen de serie.'),
('Disparar en movimiento', 'Shot On The Run', 'General', 'Des 13, Esquiva, Movilidad, Disparo a bocajarro, ataque base +4.', 'Con la acción de ataque y un arma a distancia, puedes moverte antes y después de disparar, siempre que el total no supere tu velocidad.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Conjuro silencioso', 'Silent Spell', 'Metamágica', '', 'El conjuro se lanza sin componentes verbales. Ocupa un espacio un nivel por encima del suyo.', '', ''),
('Competencia con armas sencillas', 'Simple Weapon Proficiency', 'General', '', 'Haces las tiradas de ataque con las armas sencillas con normalidad.', 'Con un arma con la que no eres competente sufres −4 al ataque.', 'Todos salvo druidas, monjes, magos y algunas clases de PNJ la tienen de serie.'),
('Habilidad focalizada', 'Skill Focus', 'General', '', '+3 a todas las pruebas de la habilidad elegida.', '', 'Puedes tomarla varias veces, cada una para otra habilidad.'),
('Atrapar flechas', 'Snatch Arrows', 'General', 'Des 15, Desviar flechas, Ataque sin armas mejorado.', 'Al usar Desviar flechas puedes atrapar el proyectil en vez de solo desviarlo. Si es un arma arrojadiza puedes devolvérsela al instante a quien te la lanzó, aunque no sea tu turno, o guardarla. Necesitas al menos una mano libre.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Conjuro focalizado', 'Spell Focus', 'General', '', '+1 a la CD de las salvaciones contra tus conjuros de la escuela elegida.', '', 'Puedes tomarla varias veces, cada una para otra escuela.'),
('Maestría de conjuros', 'Spell Mastery', 'Especial', 'Nivel de mago 1.º.', 'Cada vez que la tomas eliges tantos conjuros que ya conozcas como tu modificador de Inteligencia. A partir de ahí puedes prepararlos sin consultar el libro de conjuros.', 'Sin esta dote necesitas el libro para preparar todos tus conjuros, salvo leer magia.', ''),
('Penetración de conjuros', 'Spell Penetration', 'General', '', '+2 a las pruebas de nivel de lanzador (1d20 + nivel) para superar la resistencia a conjuros de una criatura.', '', ''),
('Carga vigorosa', 'Spirited Charge', 'General', 'Montar 1 rango, Combate montado, Ataque al paso.', 'Montado y cargando, haces el doble de daño con un arma cuerpo a cuerpo (o el triple con una lanza de caballería).', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Ataque súbito', 'Spring Attack', 'General', 'Des 13, Esquiva, Movilidad, ataque base +4.', 'Con la acción de ataque y un arma cuerpo a cuerpo, puedes moverte antes y después de atacar sin superar tu velocidad. Moverte así no provoca ataque de oportunidad del enemigo al que atacas (sí de los demás).', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Sigiloso', 'Stealthy', 'General', '', '+2 a todas las pruebas de Esconderse y de Moverse sigilosamente.', '', ''),
('Conjuro inmóvil', 'Still Spell', 'Metamágica', '', 'El conjuro se lanza sin componentes somáticos. Ocupa un espacio un nivel por encima del suyo.', '', ''),
('Golpe aturdidor', 'Stunning Fist', 'General', 'Des 13, Sab 13, Ataque sin armas mejorado, ataque base +8.', 'Debes declararla antes de tirar el ataque (si fallas, se pierde el intento). El enemigo dañado por tu ataque sin armas debe superar una salvación de Fortaleza (CD 10 + ½ tu nivel de personaje + tu modificador de Sabiduría) o queda aturdido hasta tu siguiente turno. Puedes usarla una vez al día por cada cuatro niveles de personaje.', '', 'Un monje la gana de serie a nivel 1 y la usa una vez por cada cuatro niveles de monje. Un guerrero puede elegirla como dote adicional.'),
('Dureza', 'Toughness', 'General', '', 'Ganas +3 puntos de golpe.', '', 'Puedes tomarla varias veces y sus efectos se acumulan.')
on conflict (name) do nothing;
insert into feats (name, name_en, kind, prerequisite, benefit, normal, special) values
('Competencia con escudo de torre', 'Tower Shield Proficiency', 'General', 'Competencia con escudos.', 'Puedes usar un escudo de torre sufriendo solo los penalizadores normales.', 'Con un escudo con el que no eres competente aplicas su penalizador de armadura a las tiradas de ataque y a las pruebas de habilidad que impliquen moverse.', 'Guerreros y paladines la tienen de serie.'),
('Rastrear', 'Track', 'General', '', 'Con una prueba de Supervivencia puedes encontrar rastros y seguirlos durante una milla; hay que repetirla cada vez que el rastro se complica. Vas a la mitad de tu velocidad (o a velocidad normal con −5 a la prueba, o al doble con −20).', 'Sin esta dote puedes usar Supervivencia para encontrar rastros, pero solo puedes seguirlos si la CD es 10 o menos.', 'Un explorador la gana de serie a nivel 1.'),
('Arrollar montado', 'Trample', 'General', 'Montar 1 rango, Combate montado.', 'Al atropellar montado, el objetivo no puede apartarse. Tu montura puede hacer un ataque de pezuña contra quien derribes, con el +4 habitual contra objetivos derribados.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Defensa con dos armas', 'Two-Weapon Defense', 'General', 'Des 15, Combatir con dos armas.', 'Con un arma doble o con dos armas (sin contar las naturales ni los golpes sin armas) ganas +1 de escudo a la CA. Si combates a la defensiva o usas la acción de defensa total, sube a +2.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Combatir con dos armas', 'Two-Weapon Fighting', 'General', 'Des 15.', 'Se reducen tus penalizadores por combatir con dos armas: 2 menos con la mano buena y 6 menos con la otra.', 'Sin esta dote, combatir con dos armas da −6 con la mano buena y −10 con la secundaria.', 'Un explorador de nivel 2 con el estilo de dos armas la tiene aunque no cumpla los requisitos. Un guerrero puede elegirla como dote adicional.'),
('Soltura con un arma', 'Weapon Finesse', 'General', 'Ataque base +1.', 'Con un arma ligera, un estoque, un látigo o una cadena con púas de tu tamaño puedes usar tu modificador de Destreza en vez del de Fuerza en las tiradas de ataque. Si llevas escudo, su penalizador de armadura se aplica a esas tiradas.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Arma focalizada', 'Weapon Focus', 'General', 'Competencia con el arma, ataque base +1.', '+1 a todas las tiradas de ataque con el arma elegida.', '', 'Puedes tomarla varias veces, cada una para un arma distinta. Un guerrero puede elegirla como dote adicional.'),
('Especialización con un arma', 'Weapon Specialization', 'General', 'Competencia con el arma, Arma focalizada con ella, nivel de guerrero 4.º.', '+2 a todas las tiradas de daño con el arma elegida.', '', 'Puedes tomarla varias veces, cada una para un arma distinta.'),
('Ataque en torbellino', 'Whirlwind Attack', 'General', 'Des 13, Int 13, Pericia en combate, Esquiva, Movilidad, Ataque súbito, ataque base +4.', 'Con la acción de ataque completo puedes renunciar a tus ataques normales y hacer en su lugar un ataque cuerpo a cuerpo, con tu bonificador de ataque base completo, contra cada enemigo a tu alcance. Renuncias también a los ataques adicionales de otras dotes o conjuros.', '', 'Un guerrero puede elegirla como dote adicional de guerrero.'),
('Ensanchar conjuro', 'Widen Spell', 'Metamágica', '', 'Un conjuro con área de ráfaga, emanación, línea o extensión duplica todas las medidas de su área. Ocupa un espacio tres niveles por encima del suyo.', '', '')
on conflict (name) do nothing;
